baseURL = 'https://Bamblix.github.io/net0.github.io'
languageCode = 'en-us'
title = 'Net0'
theme = 'PaperMod'

[params]
  description = "CTF writeups and security research"
  author = "net0"
  showReadingTime = true
  showShareButtons = false
  showPostNavLinks = true

[params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1000
  threshold = 0.4
  minMatchCharLength = 0
  keys = ["title", "permalink", "summary", "content"]
  
[params.homeInfoParams]
  Title = "Welcome to my CTF blog"
  Content = "Documenting my journey through HackTheBox and other CTF challenges"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 10

[[menu.main]]
  name = "Writeups"
  url = "/writeups/"
  weight = 20

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 30

[[menu.main]]
  name = "Search"
  url = "/search/"
  weight = 25

[markup.goldmark.renderer]
  unsafe = true

[[module.mounts]]
source = "static"
target = "static"

[markup.goldmark.renderHooks.image]
useEmbedded = "fallback"

[markup.goldmark.renderHooks.link]
useEmbedded = "fallback"

[markup]
  [markup.highlight]
    style = "github-dark"  # or try: dracula, github-dark, nord, onedark
    lineNos = false
    lineNumbersInTable = false
