baseURL = 'https://Bamblix.github.io/net0.github.io'
languageCode = 'en-us'
title = 'CTF Writeups'
theme = 'PaperMod'

[params]
  description = "CTF writeups and security research"
  author = "net0"
  showReadingTime = true
  showShareButtons = false
  showPostNavLinks = true
  
[params.homeInfoParams]
  Title = "Welcome to my CTF blog"
  Content = "Security researcher documenting my journey through HackTheBox and other CTF challenges"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 10

[[menu.main]]
  name = "Writeups"
  url = "/writeups/"
  weight = 20

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 30
